### ISSUE TITLE
Wrong characters shown when the game tries to show some non-standard characters

### ISSUE THREAD

**Issue by moechakucha** [thecatcore/Translated-Legacy#2]
![QQ图片20211006133206](https://user-images.githubusercontent.com/62203463/136145851-6ab69a7d-a455-4aaf-b46a-eda4004eea32.png)

Tried to use Chinese translation, and got this.

**Comment by moechakucha** [comment]
I'm using StationAPI 1.3.1

**Comment by thecatcore** [comment]
Fixed in 1.2.0
